name: StevyDiscordPaper
version: ${project.version}
main: me.math.stevydiscordpaper.Main
api-version: 1.16
load: STARTUP
authors: [ MathDuck ]
description: Discord Bot for Paper
commands:
  reloadconfig:
    description: Reload the config file
    usage: /reloadconfig
  discord:
    description: Reload discord bot
    usage: /discord
